#include "/Engine/Public/Platform.ush"

float4 SimpleColor;
void MainVS(
 in float4 InPosition : ATTRIBUTE0,
 out float4 OutPosition : SV_POSITION
 )
{
 // screenspace position from vb

 float2 Pos = InPosition.xy;

	Pos.xy = Pos.xy*2 - 1.0f;
	Pos.xy *= float2(1, -1);

    //OutPosition = float4(Pos, 0, 1);
	OutPosition = InPosition;
}

void MainPS(
    out float4 OutColor : SV_Target0
    )
{
    OutColor = float4(0,0,1,1);
}